name: LCUI3 Shared Library CI

on:
  push:
    branches:
      - develop
      - master
      - main
    tags:
      - 'v*'
  pull_request:

env:
  TARGET_MAJOR: 3
  TARGET_VERSION: 3.0.0
  TARGET_KIND: shared

jobs:
  build:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        mode: ['release', 'debug']
    runs-on: ${{ matrix.os }}
    name: "Build shared library on ${{ matrix.os }} (${{ matrix.mode }})"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          package-cache: true
          actions-cache-folder: '.xmake-cache'

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y             libfreetype6-dev             libpng-dev             libyaml-dev             libomp-dev             libx11-dev             ninja-build             fontconfig             libfontconfig1-dev             libjpeg-dev

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        run: xmake config -y -v -k ${{ env.TARGET_KIND }} -m ${{ matrix.mode }} --ci-env=y

      - name: Configure (Linux)
        if: runner.os == 'Linux'
        run: xmake config -y -v -k ${{ env.TARGET_KIND }} -m ${{ matrix.mode }} --ci-env=y

      - name: Build
        run: xmake -v

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: xmake test

      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run -a xmake test

      - name: Package library
        run: |
          xmake package
          xmake install -o dist/lcui-package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lcui${{ env.TARGET_MAJOR }}-${{ env.TARGET_VERSION }}-${{ env.TARGET_KIND }}-${{ matrix.mode }} (${{ runner.os }})
          path: dist/lcui-package

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
